export function toType(value: unknown): string;
export function toRawType(value: unknown): string;
export function toRawTypeLC(value: unknown): string;
export function isUndefined(value: unknown): value is undefined;
export function isNull(value: unknown): value is null;
export function isEmptyString(value: unknown): value is '';
export function isUndefinedOrNull(value: unknown): value is undefined | null;
export function isUndefinedOrNullOrEmpty(value: unknown): boolean;
export function isFunction(value: unknown): value is (...args: unknown[]) => unknown;
export function isBoolean(value: unknown): value is boolean;
export function isString(value: unknown): value is string;
export function isNumber(value: unknown): value is number;
export function isNumeric(value: unknown): boolean;
export function isPrimitive(value: unknown): value is boolean | string | number;
export function isArray(value: unknown): value is unknown[];
export function isObject(value: unknown): value is object;
export function isPlainObject(value: unknown): value is Record<string, unknown>;
export function isDate(value: unknown): value is Date;
export function isEvent(value: unknown): value is Event;
export function isFile(value: unknown): value is File;
export function isRegExp(value: unknown): value is RegExp;
export function isPromise(value: unknown): value is Promise<unknown>;
